image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
environment:
  NIX_CONFIG: "programs.nix-ld.enable = true"
  site: disintegrated.parts
repositories:
  nixpkgs: https://nixos.org/channels/nixpkgs-unstable
packages:
- nixos.ruby_4_0
- nixos.hut
- nixos.jekyll
- nixpkgs.openssl_4_0
- nixos.gcc
- nixos.gnumake
tasks:
- build: |
    cd $site
    bundle config set --local path vendor/bundle
    bundle install
    bundle exec jekyll build
- package: |
    cd $site/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz  
