image: nixos/unstable
oauth: pages.sr.ht/PAGES:RW
packages:
- nixos.ruby
- nixos.hut
- nixos.jekyll
- nixos.openssl_4_0
- nixos.gcc
- nixos.bundler
environment:
  site: disintegrated.parts
tasks:
- install-bundler: |
    sudo gem install bundler
- build: |
    cd $site
    sudo bundle install
    sudo bundle exec jekyll build
- package: |
    cd $site/_site
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz  
