# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


title: Disintegrated Parts
email: corstian@whaally.com
description: >-
  A digital playground, a collection of (un)related notes, 
  some half-baked projects and a casual dislike of the modern web.
url: "https://disintegrated.parts"
baseurl: ""
github_username:  corstian

# Build settings
plugins:
  - jekyll-feed
  - jekyll-toc

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM

collections:
  blog:
    label: blog
    output: true
    permalink: /:collection/:year-:month-:day/:name

defaults:
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "default"
      toc: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
